sudo: required
dist: trusty

#install google chrome, using addons
addons:
  google-chrome:latest

env:
  global:
language: node_js
node_js:
  - "8"
before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
  
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --global gulp --save
  - gem install sass
  - npm install
  - npm install d3@^5.7.0
  - ng build --prod amexio-chart-d3 && sh copycss.sh
  - npm pack dist/amexio-chart-d3/
  - mv amexio-chart-d3-*.tgz amexio-chart-d3.tgz   
script: 
  - cd ..
  - pwd
  - git clone https://github.com/meta-magic/d3-charts-tar.git -b v1.1
  - cd /home/travis/build/meta-magic/d3-charts-tar
  - cp -rf ../d3.amexio.github.io/amexio-chart-d3.tgz .
  - git add amexio-chart-d3.tgz
  - git commit -m "date"
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then  git push  --quiet "https://deepali-arvind:${D3CHART_TOKEN}@github.com/meta-magic/d3-charts-tar.git" HEAD:v1.1; fi
after_success: 
  - codecov
cache:
  yarn: true
